version: '3'

services:
  server:
    container_name: api_generator_user
    build: . 
    volumes:
        - ./app
        - ./node_modules:/app/node_modules

    networks:
      - host
    environment:
      - NODE_ENV=development
      - SERVER_HOST=localhost
      - SERVER_PORT=3000
      - LINK_DATABASE=mongodb://db/dev-api
    depends_on:
      - db
    links: 
      - db
    ports:
      - '3000:3000'
  db:
    image: 'mongo:4.4.6'
    container_name: database
    ports: 
     - "27017:27017"
    volumes:
      - ./data/db:/data/db    